spring.application.name=CadastroDeNinjas
# Força o nome do banco para não usar o padrão 'test'
spring.datasource.url=jdbc:h2:mem:ninjadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console (Isso é o que você disse que ele ignora)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# IMPORTANTE: Permite que o H2 apareça dentro de frames (exigido pelo navegador)
spring.h2.console.settings.web-allow-others=true

# Desabilita o aviso do JPA no log
spring.jpa.open-in-view=false


